export const dishes = [
  { id: 71, zh: "迷迭香烤羊排", de: "Rosmarin-Lammkoteletts", en: "Rosemary Roasted Lamb Chops", cat: "MAIN", price: 26.9, time: "28 min", people: "2 Personen", level: "Mittel", allergens: "G", ingredients: "Lamm, Rosmarin, Knoblauch, Kartoffeln", intro: "Saftige Lammkoteletts mit Rosmarin, Knoblauch und saisonalem Gemüse.", art: "linear-gradient(135deg,#6f2b21,#1a1412 74%)", pattern: "ring" },
  { id: 72, zh: "柠檬黄油煎三文鱼", de: "Lachs mit Zitronenbutter", en: "Pan-Seared Salmon, Lemon Butter", cat: "SEAFOOD", price: 24.9, time: "22 min", people: "1 Person", level: "Mild", allergens: "D, G", ingredients: "Lachs, Zitrone, Butter, Dill", intro: "Gebratener Lachs mit Zitronenbutter, Dill und Gemüse.", art: "linear-gradient(135deg,#b66732,#231814 75%)", pattern: "lines" },
  { id: 73, zh: "红酒慢炖牛肋条", de: "Rinderrippe in Rotwein", en: "Slow-Braised Beef Short Rib", cat: "MAIN", price: 27.9, time: "3 hr", people: "2 Personen", level: "Mittel", allergens: "L, O", ingredients: "Rind, Rotwein, Sellerie, Karotten", intro: "Langsam geschmorte Rinderrippe in kräftiger Rotweinsauce.", art: "linear-gradient(135deg,#72231d,#1a1211 76%)", pattern: "ring" },
  { id: 74, zh: "百里香脆皮鸡腿", de: "Knusprige Thymian-Hähnchenkeule", en: "Crispy Thyme Chicken Thigh", cat: "MAIN", price: 19.9, time: "30 min", people: "1 Person", level: "Mild", allergens: "A, G", ingredients: "Huhn, Thymian, Kartoffeln, Butter", intro: "Knusprige Hähnchenkeule, Thymian und Kartoffeln.", art: "linear-gradient(135deg,#a56a28,#211713 75%)", pattern: "lines" },
  { id: 75, zh: "白葡萄酒青口贝", de: "Miesmuscheln in Weisswein", en: "Mussels in White Wine", cat: "SEAFOOD", price: 18.9, time: "18 min", people: "2 Personen", level: "Mittel", allergens: "G, R, O", ingredients: "Miesmuscheln, Weisswein, Schalotten", intro: "Miesmuscheln mit Weisswein, Schalotten und Petersilie.", art: "linear-gradient(135deg,#285b4e,#171412 75%)", pattern: "dots" },
  { id: 76, zh: "奶油蘑菇意面", de: "Cremige Pilzpasta", en: "Creamy Wild Mushroom Pasta", cat: "PASTA", price: 16.9, time: "16 min", people: "1 Person", level: "Mild", allergens: "A, G", ingredients: "Pasta, Pilze, Sahne, Parmesan", intro: "Cremige Pasta mit Waldpilzen, Parmesan und Kraeutern.", art: "linear-gradient(135deg,#7d522e,#211713 75%)", pattern: "ring" },
  { id: 77, zh: "黑巧克力熔岩蛋糕", de: "Dunkler Schokoladenfondant", en: "Dark Chocolate Fondant", cat: "DESSERT", price: 9.5, time: "14 min", people: "1 Person", level: "Suess", allergens: "A, C, G", ingredients: "Schokolade, Ei, Butter, Mehl", intro: "Warmer Schokoladenkern mit Vanilleeis.", art: "linear-gradient(135deg,#4d241b,#160f0e 75%)", pattern: "dots" },
  { id: 78, zh: "香煎羊排配薄荷", de: "Lammkoteletts mit Minze", en: "Seared Lamb Chops, Mint", cat: "MAIN", price: 25.9, time: "26 min", people: "2 Personen", level: "Mittel", allergens: "G", ingredients: "Lamm, Minze, Kartoffeln, Jus", intro: "Gebratene Lammkoteletts mit Minze und Kartoffeln.", art: "linear-gradient(135deg,#9a4d2c,#211713 75%)", pattern: "lines" },
  { id: 79, zh: "香煎三文鱼配莳萝", de: "Lachs mit Dill", en: "Seared Salmon with Dill", cat: "SEAFOOD", price: 23.9, time: "20 min", people: "1 Person", level: "Mild", allergens: "D, G", ingredients: "Lachs, Dill, Zitrone, Gemuese", intro: "Lachsfilet mit Dill, Zitrone und Gemüse.", art: "linear-gradient(135deg,#8b3927,#1c1311 75%)", pattern: "dots" },
  { id: 80, zh: "黑椒牛柳", de: "Rinderfilet mit schwarzem Pfeffer", en: "Black Pepper Beef Fillet", cat: "MAIN", price: 34.5, time: "35 min", people: "2 Personen", level: "Fortgeschritten", allergens: "F, O", ingredients: "Rinderfilet, Pfeffer, Rotwein, Gemuese", intro: "Zartes Rinderfilet mit schwarzem Pfeffer, Rotwein und Gemüse.", art: "linear-gradient(135deg,#7e1e18,#190f0e 76%)", pattern: "ring" },
  { id: 81, zh: "柠檬烤全鸡", de: "Zitronen-Brathaehnchen", en: "Lemon Roast Chicken", cat: "MAIN", price: 29.9, time: "55 min", people: "3 Personen", level: "Mittel", allergens: "G", ingredients: "Huhn, Zitrone, Knoblauch, Kraeuter", intro: "Ganzes Brathähnchen mit Zitrone, Knoblauch und Kräutern.", art: "linear-gradient(135deg,#a76a2b,#211713 75%)", pattern: "lines" },
  { id: 82, zh: "蒜香黄油青口", de: "Knoblauchbutter-Miesmuscheln", en: "Garlic Butter Mussels", cat: "SEAFOOD", price: 26.7, time: "18 min", people: "2 Personen", level: "Mittel", allergens: "G, R", ingredients: "Miesmuscheln, Knoblauch, Butter", intro: "Miesmuscheln mit Knoblauchbutter und Petersilie.", art: "linear-gradient(135deg,#285a4e,#171412 76%)", pattern: "lines" },
  { id: 83, zh: "罗勒青酱意面", de: "Basilikum-Pesto-Pasta", en: "Basil Pesto Pasta", cat: "PASTA", price: 15.9, time: "15 min", people: "1 Person", level: "Mild", allergens: "A, G, H", ingredients: "Pasta, Basilikum, Parmesan, Pinienkerne", intro: "Pasta mit Basilikumpesto, Parmesan und Pinienkernen.", art: "linear-gradient(135deg,#345a36,#161512 75%)", pattern: "dots" },
  { id: 84, zh: "焦糖熔岩蛋糕", de: "Karamell-Fondant", en: "Salted Caramel Fondant", cat: "DESSERT", price: 9.9, time: "14 min", people: "1 Person", level: "Suess", allergens: "A, C, G", ingredients: "Karamell, Ei, Butter, Vanille", intro: "Warmer Karamellkern mit Vanilleeis.", art: "linear-gradient(135deg,#a86b26,#211713 75%)", pattern: "ring" },
  { id: 85, zh: "迷迭香烤羊排", de: "Rosmarin-Lammkarree", en: "Rosemary Roasted Rack of Lamb", cat: "MAIN", price: 31.9, time: "32 min", people: "2 Personen", level: "Mittel", allergens: "G", ingredients: "Lammkarree, Rosmarin, Gemuese", intro: "Lammkarree mit Rosmarin und saisonalem Gemüse.", art: "linear-gradient(135deg,#8a3e28,#211713 75%)", pattern: "lines" }
];

export const services = [
  ["water", "加水", "WASSER"],
  ["utensils", "餐具", "BESTECK"],
  ["napkin", "纸巾", "SERVIETTEN"],
  ["takeaway", "打包", "MITNEHMEN"],
  ["clear", "收空盘", "ABRAEUMEN"],
  ["pay", "结账", "BEZAHLEN"]
] as const;

export const orderStatuses = ["新订单", "制作中", "可上菜", "已完成"] as const;
