const art = {
  food: "linear-gradient(135deg,#7e3d25,#171210 75%)",
  sushi: "linear-gradient(135deg,#b56b3d,#171210 75%)",
  drink: "linear-gradient(135deg,#8b622f,#171210 75%)"
};

function item(sku, kind, category, de, en, zh, price, allergens, ingredients, station = kind === "drink" ? "bar" : kind === "sushi" ? "sushi" : "kitchen", options = {}) {
  return {
    id: `photo-${sku.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
    sku,
    kind,
    cat: category,
    zh,
    de,
    en,
    price,
    allergens,
    ingredients,
    intro: ingredients,
    time: options.time || (kind === "drink" ? "2 min" : kind === "sushi" ? "10 min" : "20 min"),
    people: options.people || "1 Person",
    level: options.level || "Mild",
    art: art[kind],
    pattern: options.pattern || "lines",
    station
  };
}

export const photoMenuDishes = [
  item("R1", "food", "RAMEN", "Ramen mit Gemüse", "Ramen with Vegetables", "蔬菜拉面", 12.5, ["A", "C", "F"], "Ramen, Gemüse, Ei"),
  item("R2", "food", "RAMEN", "Ramen mit Huhn", "Ramen with Chicken", "鸡肉拉面", 13.5, ["A", "C", "F"], "Ramen, Huhn, Gemüse, Ei"),
  item("R3", "food", "RAMEN", "Ramen mit Rind", "Ramen with Beef", "牛肉拉面", 14.5, ["A", "C", "F"], "Ramen, Rind, Gemüse, Ei"),
  item("R4", "food", "RAMEN", "Ramen mit Garnelen", "Ramen with Shrimp", "虾仁拉面", 14.5, ["A", "B", "C", "F"], "Ramen, Garnelen, Gemüse, Ei"),
  item("T1", "food", "SPECIALS", "Szechuan Rind", "Szechuan Boiled Beef", "水煮牛肉", 17.9, ["A", "C", "F", "N"], "Rind, Gemüse, Szechuan-Chili, Koriander"),
  item("T2", "food", "SPECIALS", "Scharfes knuspriges Huhn", "Spicy Crispy Chicken", "辣子鸡", 14.9, ["A", "F", "N"], "Huhn, Gemüse, Koriander"),
  item("T3", "food", "SPECIALS", "Scharfe knusprige Garnelen", "Spicy Crispy King Prawns", "香辣虾", 18.9, ["A", "B", "F", "N"], "Garnelen, Gemüse, Koriander"),
  item("T4", "food", "SPECIALS", "Mapo Tofu", "Mapo Tofu", "麻婆豆腐", 11.9, ["A", "F", "N"], "Tofu, Gemüse, Szechuan-Chili"),
  item("T4C", "food", "SPECIALS", "Mapo Tofu mit Huhn", "Mapo Tofu with Chicken", "鸡肉麻婆豆腐", 12.9, ["A", "F", "N"], "Tofu, Huhn, Gemüse, Szechuan-Chili"),
  item("A1", "food", "BAO", "Veggie Bao (2 Stück)", "Veggie Bao (2 pieces)", "素食刈包（2个）", 12.9, ["A", "F"], "Salat, Tofu, Mango, Karotten, Gurken, Soße"),
  item("A2", "food", "BAO", "Chicken Bao (2 Stück)", "Chicken Bao (2 pieces)", "鸡肉刈包（2个）", 13.9, ["A", "F"], "Hühnerfilet, Karotten, Gurken, Soße"),
  item("A3", "food", "BAO", "Bulgogi Bao (2 Stück)", "Bulgogi Bao (2 pieces)", "韩式牛肉刈包（2个）", 13.9, ["A", "F"], "Koreanisches Rindfleisch, Karotten, Gurken"),
  item("A4", "food", "BAO", "Crispy Duck Bao (2 Stück)", "Crispy Duck Bao (2 pieces)", "脆皮鸭刈包（2个）", 13.9, ["A", "F"], "Ente, Karotten, Gurken, Soße"),
  item("H1", "food", "HOT POT", "Veggie Hot Pot", "Veggie Hot Pot", "素食火锅", 23.9, ["A", "E", "N"], "Saison-Gemüse, Tofu, Glasnudel, Udon, Reiskuchen, Gyoza"),
  item("H2", "food", "HOT POT", "Beef Hot Pot", "Beef Hot Pot", "牛肉火锅", 25.9, ["A", "E", "N"], "Saison-Gemüse, Tofu, Glasnudel, Reiskuchen, Rindfleisch"),
  item("H3", "food", "HOT POT", "Seafood Hot Pot", "Seafood Hot Pot", "海鲜火锅", 25.9, ["A", "B", "E", "N"], "Saison-Gemüse, Tofu, Glasnudel, Reiskuchen, Meeresfrüchte"),
  item("H4", "food", "HOT POT", "Lamm Hot Pot", "Lamb Hot Pot", "羊肉火锅", 25.9, ["A", "B", "E", "N"], "Saison-Gemüse, Tofu, Glasnudel, Reiskuchen, Lammfleisch"),
  item("N1-6", "sushi", "NIGIRI", "Sake Set 6 Stück", "Salmon Nigiri Set 6 pcs", "三文鱼握寿司 6个", 9.9, ["B", "D"], "Lachs, Reis"),
  item("N1-10", "sushi", "NIGIRI", "Sake Set 10 Stück", "Salmon Nigiri Set 10 pcs", "三文鱼握寿司 10个", 14.9, ["B", "D"], "Lachs, Reis"),
  item("N2-6", "sushi", "NIGIRI", "Mix Set 6 Stück", "Mixed Nigiri Set 6 pcs", "混合握寿司 6个", 9.9, ["B", "D"], "Lachs, Thunfisch, Hamachi, Garnelen, Aal, Avocado"),
  item("N2-10", "sushi", "NIGIRI", "Mix Set 10 Stück", "Mixed Nigiri Set 10 pcs", "混合握寿司 10个", 14.9, ["B", "D"], "Lachs, Thunfisch, Hamachi, Garnelen, Aal, Avocado"),
  item("N3-6", "sushi", "NIGIRI", "Sake Maguro Set 6 Stück", "Salmon Tuna Nigiri Set 6 pcs", "三文鱼金枪鱼握寿司 6个", 10.9, ["D"], "Lachs, Thunfisch"),
  item("N3-10", "sushi", "NIGIRI", "Sake Maguro Set 10 Stück", "Salmon Tuna Nigiri Set 10 pcs", "三文鱼金枪鱼握寿司 10个", 15.9, ["D"], "Lachs, Thunfisch"),
  item("N4-6", "sushi", "NIGIRI", "Maguro Set 6 Stück", "Tuna Nigiri Set 6 pcs", "金枪鱼握寿司 6个", 11.9, ["D"], "Thunfisch"),
  item("N4-10", "sushi", "NIGIRI", "Maguro Set 10 Stück", "Tuna Nigiri Set 10 pcs", "金枪鱼握寿司 10个", 16.9, ["D"], "Thunfisch"),
  item("M1", "sushi", "MAKI", "Kappa Maki 12 Stück", "Cucumber Maki 12 pcs", "黄瓜卷 12个", 7.9, [], "Gurke, Reis, Nori"),
  item("M2", "sushi", "MAKI", "Sake Maki 12 Stück", "Salmon Maki 12 pcs", "三文鱼卷 12个", 8.5, ["D"], "Lachs, Reis, Nori"),
  item("M3", "sushi", "MAKI", "Avocado Maki 12 Stück", "Avocado Maki 12 pcs", "牛油果卷 12个", 8.5, ["D"], "Avocado, Reis, Nori"),
  item("M5", "sushi", "MAKI SESAM", "Avocado Mango Maki 8 Stück", "Avocado Mango Maki 8 pcs", "牛油果芒果卷 8个", 6.5, ["N"], "Avocado, Mango, Reis, Sesam"),
  item("M6", "sushi", "MAKI SESAM", "Avocado Ebi Maki 8 Stück", "Avocado Shrimp Maki 8 pcs", "牛油果虾卷 8个", 8.5, ["B", "N"], "Avocado, Garnelen, Reis, Sesam"),
  item("M7", "sushi", "MAKI SESAM", "Avocado Sake Maki 8 Stück", "Avocado Salmon Maki 8 pcs", "牛油果三文鱼卷 8个", 8.5, ["D", "N"], "Avocado, Lachs, Reis, Sesam"),
  item("S1-9", "sushi", "SASHIMI", "Sake Set 9 Stück", "Salmon Sashimi Set 9 pcs", "三文鱼刺身 9个", 16.9, ["D"], "Lachs"),
  item("S1-18", "sushi", "SASHIMI", "Sake Set 18 Stück", "Salmon Sashimi Set 18 pcs", "三文鱼刺身 18个", 28.9, ["D"], "Lachs"),
  item("S2-9", "sushi", "SASHIMI", "Sake Maguro Set 9 Stück", "Salmon Tuna Sashimi 9 pcs", "三文鱼金枪鱼刺身 9个", 17.9, ["D"], "Lachs, Thunfisch"),
  item("S2-18", "sushi", "SASHIMI", "Sake Maguro Set 18 Stück", "Salmon Tuna Sashimi 18 pcs", "三文鱼金枪鱼刺身 18个", 29.9, ["D"], "Lachs, Thunfisch"),
  item("S3-9", "sushi", "SASHIMI", "Mix Set 9 Stück", "Mixed Sashimi Set 9 pcs", "混合刺身 9个", 17.9, ["B", "D"], "Lachs, Thunfisch, Hamachi"),
  item("S3-18", "sushi", "SASHIMI", "Mix Set 18 Stück", "Mixed Sashimi Set 18 pcs", "混合刺身 18个", 29.9, ["B", "D"], "Lachs, Thunfisch, Hamachi"),
  item("X1", "sushi", "CHIRI ROLLS", "Rainbow Roll 8 Stück", "Rainbow Roll 8 pcs", "彩虹卷 8个", 15.9, ["C", "F", "D"], "Lachs, Thunfisch, Hamachi, Avocado, Kresse"),
  item("X2", "sushi", "CHIRI ROLLS", "Crunchy Salmon Roll 8 Stück", "Crunchy Salmon Roll 8 pcs", "脆皮三文鱼卷 8个", 14.9, ["A", "C", "D", "F"], "Lachstempura, Salat, Crispy Panko, Mayo, Teriyaki"),
  item("X3", "sushi", "CHIRI ROLLS", "Pink Alaska 8 Stück", "Pink Alaska Roll 8 pcs", "粉色阿拉斯加卷 8个", 12.9, ["D", "N"], "Lachs, Cream Cheese, Avocado, Masago"),
  item("X4", "sushi", "CHIRI ROLLS", "Spicy Tuna 8 Stück", "Spicy Tuna Roll 8 pcs", "辣金枪鱼卷 8个", 15.9, ["D", "N"], "Thunfisch, Avocado, Masago, Spicy Mayo"),
  item("X5", "sushi", "CHIRI ROLLS", "Dragon Roll 8 Stück", "Dragon Roll 8 pcs", "龙卷 8个", 16.9, ["A", "C", "D"], "Garnelen, Avocado, flambierter Aal, Sushi-Soße"),
  item("X6", "sushi", "CHIRI ROLLS", "Agamo Roll 8 Stück", "Agamo Roll 8 pcs", "鸭肉卷 8个", 12.9, ["A", "F"], "Knusperente, Gurken, Jungzwiebel, Teriyaki"),
  item("X7", "sushi", "CHIRI ROLLS", "Sweet Power 8 Stück", "Sweet Power Roll 8 pcs", "甜力卷 8个", 13.9, ["D", "F"], "Avocado, Mango, flambierter Lachs"),
  item("X8", "sushi", "CHIRI ROLLS", "Sweet Green 8 Stück", "Sweet Green Roll 8 pcs", "甜绿卷 8个", 12.9, ["C", "F"], "Süßkartoffeltempura, Mango, Gurke, Basilikum"),
  item("X9", "sushi", "CHIRI ROLLS", "Mikado Roll 8 Stück", "Mikado Roll 8 pcs", "御卷 8个", 12.9, ["A", "E", "F"], "Erdnuss, Avocado, Kresse"),
  item("B1", "food", "MAIN DISHES", "Sesam Chicken", "Sesame Chicken", "芝麻鸡", 13.9, ["A", "C", "F", "N"], "Hühnerstreifen, Gemüse, Sesam"),
  item("B2", "food", "MAIN DISHES", "Red Thai Curry Chicken", "Red Thai Curry Chicken", "红咖喱鸡", 13.9, [], "Hühnerfleisch, Kokosmilch, Gemüse, Basilikum"),
  item("B3", "food", "MAIN DISHES", "Hawaii Chicken", "Hawaii Chicken", "夏威夷鸡", 13.9, ["A"], "Ananas, Mango, Hühnerfleisch, Gemüse, Kokosmilch"),
  item("B4", "food", "MAIN DISHES", "Crispy Panko Chicken", "Crispy Panko Chicken", "脆皮鸡", 13.9, ["A", "C", "F", "N"], "Hühnerfilet, Panko, Gemüse"),
  item("B5", "food", "MAIN DISHES", "Chili Beef", "Chili Beef", "辣椒牛肉", 14.9, ["F"], "Rind, Gemüse, frischer Chili"),
  item("B6", "food", "MAIN DISHES", "Bulgogi", "Bulgogi Beef", "韩式烤牛肉", 14.9, ["F", "N"], "Rindfleisch, Zwiebel, Gemüse"),
  item("B7", "food", "MAIN DISHES", "Gongbao Crispy Duck", "Gongbao Crispy Duck", "宫保脆皮鸭", 14.9, ["A", "F"], "Ente, Gemüse, trockener Chili"),
  item("B8", "food", "MAIN DISHES", "Sake Teriyaki", "Salmon Teriyaki", "照烧三文鱼", 14.9, ["A", "D", "F", "N"], "Lachs, Gemüse, Teriyaki-Soße"),
  item("B9", "food", "MAIN DISHES", "Tom Yam Prawns", "Tom Yam Prawns", "冬阴功虾", 17.9, ["B"], "Garnelen, Gemüse, Thai-Kräuter"),
  item("B10", "food", "MAIN DISHES", "Tofu Pak Choi", "Tofu Pak Choi", "豆腐上海青", 12.9, ["F"], "Tofu, Pak Choi, Gemüse"),
  item("B11", "food", "MAIN DISHES", "Nasi Goreng", "Nasi Goreng", "印尼炒饭", 11.9, ["A", "C", "F"], "Eierreis, Gemüse, Entenfleisch, gelbes Curry"),
  item("B12", "food", "MAIN DISHES", "Veggie Tteokbokki", "Veggie Tteokbokki", "素食辣炒年糕", 11.9, ["A", "F", "N"], "Reiskuchen, Gemüse, koreanisch"),
  item("B13", "food", "MAIN DISHES", "Shrimps Tteokbokki", "Shrimp Tteokbokki", "虾仁辣炒年糕", 13.9, ["A", "B", "F", "N"], "Reiskuchen, Gemüse, Garnelen"),
  item("B14", "food", "MAIN DISHES", "Veggie Dumplings 12 Stück", "Veggie Dumplings 12 pcs", "素食饺子 12个", 12.9, ["A", "F", "N"], "Teigtaschen, Gemüse, Glasnudel"),
  item("B15", "food", "MAIN DISHES", "Chicken Dumplings 12 Stück", "Chicken Dumplings 12 pcs", "鸡肉饺子 12个", 12.9, ["A", "F", "N"], "Teigtaschen, Hühnerfleisch, Bärlauch"),
  item("V1", "food", "STARTER", "Edamame", "Edamame", "毛豆", 4.5, ["F"], "Sojabohnen, Meersalz"),
  item("V2", "food", "STARTER", "Summerrolls Veggie 2 Stück", "Veggie Summer Rolls 2 pcs", "素春卷 2个", 6.9, ["A", "E", "F"], "Gurke, Mango, Avocado, Reisnudeln, Basilikum"),
  item("V3", "food", "STARTER", "Summerrolls Shrimp 2 Stück", "Shrimp Summer Rolls 2 pcs", "虾仁春卷 2个", 7.9, ["A", "B", "E", "F"], "Gurke, Mango, Avocado, Garnelen, Basilikum"),
  item("V4", "food", "STARTER", "Mini Springroll 6 Stück", "Mini Spring Rolls 6 pcs", "迷你春卷 6个", 3.9, ["A", "F", "N"], "Gemüse, Teig"),
  item("V5", "food", "STARTER", "Veggie Gyoza 6 Stück", "Veggie Gyoza 6 pcs", "素食锅贴 6个", 5.9, ["A", "C", "F"], "Teigtaschen, Gemüse"),
  item("V6", "food", "STARTER", "Chicken Gyoza 6 Stück", "Chicken Gyoza 6 pcs", "鸡肉锅贴 6个", 5.9, ["A", "C", "F"], "Teigtaschen, Hühnerfleisch, Gemüse"),
  item("V7", "food", "STARTER", "Beef Gyoza 6 Stück", "Beef Gyoza 6 pcs", "牛肉锅贴 6个", 5.9, ["A", "C", "F"], "Teigtaschen, Rindfleisch, Gemüse"),
  item("V8", "food", "STARTER", "Takoyaki 6 Stück", "Takoyaki 6 pcs", "章鱼烧 6个", 5.9, ["A", "C", "F", "G", "R"], "Oktopus-Bällchen, Mayo-Soße"),
  item("V9", "food", "STARTER", "Kimchi Salat", "Kimchi Salad", "泡菜沙拉", 4.5, ["F", "D"], "Koreanischer scharfer Salat"),
  item("V10", "food", "STARTER", "Avocado Salat", "Avocado Salad", "牛油果沙拉", 6.9, ["D", "N"], "Salat, Avocado"),
  item("V11", "food", "STARTER", "Salmon Tatar Salat", "Salmon Tartar Salad", "三文鱼塔塔沙拉", 8.9, ["D", "N"], "Lachs-Tatar, Mango, Avocado, Salat"),
  item("V12", "food", "STARTER", "Cocos Shrimp 5 Stück", "Coconut Shrimp 5 pcs", "椰香虾 5个", 5.9, ["A", "B"], "Gebackene Garnelen"),
  item("V13", "food", "STARTER", "Chili Wonton", "Chili Wonton", "红油抄手", 5.5, ["A", "B", "F", "N"], "Hühnerfleisch, Garnelen, Koriander"),
  item("V14", "food", "STARTER", "Miso Soup", "Miso Soup", "味噌汤", 3.9, ["A", "F"], "Miso, Tofu, Algen"),
  item("V15", "food", "STARTER", "Wonton Soup", "Wonton Soup", "云吞汤", 5.5, ["A", "B", "F", "N"], "Hühnerfleisch, Garnelen, Gemüse"),
  item("V16", "food", "STARTER", "Tom Yam Gung Soup", "Tom Yam Gung Soup", "冬阴功汤", 5.9, ["B"], "Garnelen, Gemüse, Koriander"),
  item("V17", "food", "STARTER", "Tom Kha Gai Soup", "Tom Kha Gai Soup", "椰奶鸡汤", 5.5, ["F"], "Hühnerfleisch, Gemüse, Kokosmilch"),
  item("V18", "food", "STARTER", "Shrimp Dumplings 4 Stück", "Shrimp Dumplings 4 pcs", "虾饺 4个", 5.9, ["A", "B", "F", "N"], "Gedämpfte Teigtaschen, Garnelen"),
  item("U1", "food", "FRIED UDON", "Yaki Udon Yasai", "Yaki Udon Yasai", "蔬菜炒乌冬", 10.9, ["A", "F", "N"], "Udon, Gemüse"),
  item("U2", "food", "FRIED UDON", "Yaki Udon Toriniku", "Yaki Udon Chicken", "鸡肉炒乌冬", 11.9, ["A", "F", "N"], "Udon, Hühnerfleisch, Gemüse"),
  item("U3", "food", "FRIED UDON", "Yaki Udon Gyuniku", "Yaki Udon Beef", "牛肉炒乌冬", 12.9, ["A", "F", "N"], "Udon, Rindfleisch, Gemüse"),
  item("U4", "food", "FRIED UDON", "Yaki Udon Kamoniku", "Yaki Udon Duck", "鸭肉炒乌冬", 12.9, ["A", "F", "N"], "Udon, Entenfleisch, Gemüse"),
  item("U5", "food", "FRIED UDON", "Yaki Udon Ebi", "Yaki Udon Shrimp", "虾仁炒乌冬", 12.9, ["A", "F", "D", "N"], "Udon, Garnelen, Gemüse"),
  item("SIDE-RICE", "food", "SIDE DISHES", "Reis", "Steamed Rice", "米饭", 2.0, [], "Gekochter Reis"),
  item("SIDE-FRIED-RICE", "food", "SIDE DISHES", "Gebratener Reis", "Fried Rice", "炒饭", 4.9, ["C", "F"], "Ei, Gemüse"),
  item("D1", "food", "DESSERT", "Mochi", "Mochi", "麻薯", 6.9, ["A", "G"], "Mochi, Eis"),
  item("D2", "food", "DESSERT", "Matcha Tiramisu", "Matcha Tiramisu", "抹茶提拉米苏", 5.9, ["A", "C", "G"], "Matcha, Mascarpone, Biskuit"),
  item("D3", "food", "DESSERT", "Apfel Gyoza 5 Stück", "Apple Gyoza 5 pcs", "苹果饺子 5个", 5.9, ["A", "C"], "Apfel, Teigtaschen"),
  item("DR-COLA", "drink", "NON-ALCOHOLIC", "Cola / Cola Zero", "Cola / Cola Zero", "可乐 / 无糖可乐", 3.8, [], "0.33L"),
  item("DR-EISTEE", "drink", "NON-ALCOHOLIC", "Eistee / Fanta", "Iced Tea / Fanta", "冰茶 / 芬达", 3.8, [], "0.33L"),
  item("DR-WATER", "drink", "NON-ALCOHOLIC", "Römerquelle Still / Prickelnd", "Still / Sparkling Water", "静水 / 气泡水", 3.2, [], "0.50L"),
  item("DR-ALOE", "drink", "NON-ALCOHOLIC", "Aloe Vera", "Aloe Vera", "芦荟汁", 4.8, [], "0.50L"),
  item("DR-APPLE", "drink", "NON-ALCOHOLIC", "Apfelsaft", "Apple Juice", "苹果汁", 3.3, [], "0.33L"),
  item("DR-ORANGE", "drink", "NON-ALCOHOLIC", "Orangensaft", "Orange Juice", "橙汁", 3.3, [], "0.33L"),
  item("DR-REDBULL", "drink", "NON-ALCOHOLIC", "Red Bull", "Red Bull", "红牛", 3.9, [], "0.25L"),
  item("BEER-WIESEL-FASS", "drink", "BEER", "Wieselburger Fass", "Wieselburger Draft Beer", "维瑟堡生啤", 3.9, ["A"], "0.33L"),
  item("BEER-WIESEL-STAMM", "drink", "BEER", "Wieselburger Stammbräu", "Wieselburger Lager", "维瑟堡啤酒", 4.9, ["A"], "0.50L"),
  item("BEER-NONALC", "drink", "BEER", "Alkoholfreies Bier", "Non-alcoholic Beer", "无酒精啤酒", 4.5, ["A"], "Flasche"),
  item("BEER-JAPAN", "drink", "BEER", "Japanisches Bier", "Japanese Beer", "日本啤酒", 4.5, ["A"], "Flasche"),
  item("WINE-WHITE", "drink", "WINE APERITIF", "Weißwein Grüner Veltliner 1/8", "White Wine Grüner Veltliner 1/8", "白葡萄酒 1/8", 4.5, ["O"], "0.125L"),
  item("WINE-RED", "drink", "WINE APERITIF", "Rotwein Zweigelt 1/8", "Red Wine Zweigelt 1/8", "红葡萄酒 1/8", 4.5, ["O"], "0.125L"),
  item("WINE-SPRITZER", "drink", "WINE APERITIF", "Weißer Spritzer", "White Wine Spritzer", "白葡萄酒苏打", 3.5, ["O"], "0.25L"),
  item("APEROL", "drink", "WINE APERITIF", "Aperol", "Aperol", "阿佩罗", 4.5, ["O"], "Aperol"),
  item("APEROL-PROSECCO", "drink", "WINE APERITIF", "Aperol Prosecco", "Aperol Prosecco", "阿佩罗起泡酒", 5.5, ["O"], "Prosecco"),
  item("HUGO", "drink", "WINE APERITIF", "Hugo", "Hugo", "雨果鸡尾酒", 5.5, ["O"], "Holunder, Minze, Limette"),
  item("SAKE", "drink", "WINE APERITIF", "Sake", "Sake", "清酒", 5.5, [], "0.10L"),
  item("COFFEE-ESPRESSO", "drink", "COFFEE", "Espresso", "Espresso", "浓缩咖啡", 2.9, ["G"], "Kaffee"),
  item("COFFEE-CAPPUCCINO", "drink", "COFFEE", "Cappuccino", "Cappuccino", "卡布奇诺", 4.2, ["G"], "Kaffee, Milch"),
  item("COFFEE-LATTE", "drink", "COFFEE", "Latte Macchiato", "Latte Macchiato", "拿铁咖啡", 4.5, ["G"], "Kaffee, Milch"),
  item("TEA", "drink", "TEA", "Jasmintee, Grüntee, Schwarztee", "Jasmine, Green or Black Tea", "茉莉花茶、绿茶、红茶", 3.5, [], "Tee")
];
