import { useQuery } from "@tanstack/react-query";
import type { ApiCatalogProduct, MenuThemeId } from "@zhaoyun/contracts";
import type { Product } from "@zhaoyun/domain";
import { DEFAULT_MENU_THEME } from "@zhaoyun/domain";
import { mapApiProduct, restaurantApi } from "./api";
import bundled from "./bundled-catalog.json";

const cacheKey = "zy_catalog_cache_v3";

interface Catalog {
  products: Product[];
  theme: MenuThemeId;
}

/**
 * The menu the app ships with: exactly what a fresh server seeds, generated by
 * scripts/bundle-catalog.mjs through the server's own catalogue code path so
 * the product ids match. That is the whole point — the demo menu this replaces
 * invented ids the server had never heard of, so every order placed from it was
 * rejected for good on reconnect.
 *
 * It is a last resort. A tablet that has reached the server prefers what the
 * server said, because prices and availability are edited there.
 */
const bundledCatalog: Product[] = (bundled as unknown as ApiCatalogProduct[]).map(mapApiProduct);

function cachedCatalog(): Catalog {
  try {
    const cached = JSON.parse(localStorage.getItem(cacheKey) || "null") as Catalog | null;
    return cached && Array.isArray(cached.products) && cached.products.length
      ? cached
      : { products: bundledCatalog, theme: DEFAULT_MENU_THEME };
  } catch {
    return { products: bundledCatalog, theme: DEFAULT_MENU_THEME };
  }
}

export function useCatalog() {
  const query = useQuery({
    queryKey: ["catalog"],
    queryFn: async (): Promise<Catalog> => {
      const { products, theme } = await restaurantApi.catalog();
      const catalog = { products: products.map(mapApiProduct), theme: theme ?? DEFAULT_MENU_THEME };
      localStorage.setItem(cacheKey, JSON.stringify(catalog));
      return catalog;
    },
    initialData: cachedCatalog,
    initialDataUpdatedAt: 0,
    staleTime: 30_000,
    retry: 1,
    networkMode: "offlineFirst"
  });

  // Identity, not contents: a served catalogue is a fresh array even when it
  // happens to be identical to the one we ship.
  return { ...query, usingBundledMenu: query.data?.products === bundledCatalog };
}
