import { useQuery } from "@tanstack/react-query";
import type { ApiCatalogProduct } from "@zhaoyun/contracts";
import type { Product } from "@zhaoyun/domain";
import { mapApiProduct, restaurantApi } from "./api";
import bundled from "./bundled-catalog.json";

const cacheKey = "zy_catalog_cache_v2";

/**
 * The menu the app ships with: exactly what a fresh server seeds, generated by
 * scripts/bundle-catalog.mjs through the server's own catalogue code path so
 * the product ids match. That is the whole point — the demo menu this replaces
 * invented ids the server had never heard of, so every order placed from it was
 * rejected for good on reconnect.
 *
 * It is a last resort. A tablet that has reached the server prefers what the
 * server said, because prices and availability are edited there.
 */
const bundledCatalog: Product[] = (bundled as unknown as ApiCatalogProduct[]).map(mapApiProduct);

function cachedCatalog(): Product[] {
  try {
    const cached = JSON.parse(localStorage.getItem(cacheKey) || "null") as Product[] | null;
    return Array.isArray(cached) && cached.length ? cached : bundledCatalog;
  } catch {
    return bundledCatalog;
  }
}

export function useCatalog() {
  const query = useQuery({
    queryKey: ["catalog"],
    queryFn: async () => {
      const { products } = await restaurantApi.catalog();
      const catalog = products.map(mapApiProduct);
      localStorage.setItem(cacheKey, JSON.stringify(catalog));
      return catalog;
    },
    initialData: cachedCatalog,
    initialDataUpdatedAt: 0,
    staleTime: 30_000,
    retry: 1,
    networkMode: "offlineFirst"
  });

  // Identity, not contents: a served catalogue is a fresh array even when it
  // happens to be identical to the one we ship.
  return { ...query, usingBundledMenu: query.data === bundledCatalog };
}
